[package]
name = "tauri-plugin-pinia"
description = "Persistent Pinia stores for Tauri"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/ferreira-tb/tauri-plugin-pinia"
repository = "https://github.com/ferreira-tb/tauri-plugin-pinia"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
keywords = ["plugin", "tauri", "tauri-plugin", "vue", "pinia"]

[dependencies.tauri]
version = "2.0.0-beta.22"
