[package]
name = "tauri-plugin-pinia"
description = "Persistent Pinia stores for Tauri"
version = "0.1.1"
edition = "2021"
links = "tauri-plugin-pinia"
homepage = "https://github.com/ferreira-tb/tauri-plugin-pinia"
repository = "https://github.com/ferreira-tb/tauri-plugin-pinia"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
keywords = ["plugin", "tauri", "tauri-plugin", "vue", "pinia"]

[dependencies]
serde = "1.0.203"
tauri = "2.0.0-beta.23"
tauri-plugin-store = "2.0.0-beta.9"
thiserror = "1.0.61"

[build-dependencies.tauri-plugin]
version = "2.0.0-beta.18"
features = ["build"]
