[workspace]
members = ["plugin", "packages/playground/src-tauri"]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://github.com/ferreira-tb/tauri-plugin-pinia"
repository = "https://github.com/ferreira-tb/tauri-plugin-pinia"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
keywords = ["plugin", "tauri", "tauri-plugin", "vue", "pinia"]

[workspace.lints.rust]
async_fn_in_trait = "allow"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
filetype_is_file = "deny"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
rc_buffer = "deny"
rc_mutex = "deny"
rest_pat_in_fully_bound_structs = "deny"

[workspace.lints.clippy.pedantic]
level = "deny"
priority = -1
