[package]
name = "playground"
version = "0.5.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[build-dependencies.tauri-build]
version = "2.0.0-rc"
features = []

[dependencies]
tauri-plugin-process = "2.0.0-rc"
tauri-plugin-window-state = "2.0.0-rc"

[dependencies.tauri]
version = "2.0.0-rc"
features = ["devtools", "protocol-asset"]

[dependencies.tauri-plugin-pinia]
path = "../../../plugin"
default-features = false
features = ["ahash", "tracing"]

[features]
async-pinia = ["tauri-plugin-pinia/async-pinia"]
