[package]
name = "playground"
version = "0.1.2"
edition.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["devtools", "protocol-asset"] }
tauri-plugin-window-state = "2.0.0-beta.11"

[dependencies.tauri-plugin-pinia]
path = "../../../plugin"
