name: Publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: pnpm/action-setup@v3
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: |
          sudo apt-get update
          sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1

      - run: pnpm run lint
      - run: cargo publish -p tauri-plugin-pinia --allow-dirty --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

      - run: pnpm build
      - run: pnpm publish -F tauri-plugin-pinia --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
